version: '3.8'

services:
  rchan5:
    image: ghcr.io/rtainjapan/rchan5:latest
    container_name: rchan5
    environment:
      - BROADCASTTER_USERNAME=
      - MODERATOR_USERNAME=
    volumes:
      - ./data:/usr/src/app/data
    restart: always
